

#H2 DB 설정
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/kkeujeok
    username: sa
    password:

  #JPA 설정
  jpa:
    database-platform:
    hibernate:
      ddl-auto: create # validate

    #배포 할 떄는 open-in-view false 설정
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true