#DB 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${{ secrets.RDS_URL }}:3306/kkeujeok_rds_name?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${{ secrets.RDS_USERNAME }}
    password: ${{ secrets.RDS_PASSWORD }}

  #JPA 설정
  jpa:
    database-platform:
    hibernate:
      ddl-auto: create

    #배포 할 떄는 open-in-view false 설정
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
